name: charzzk-docker-compose-swagger-ui

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - "8000:8080"
    restart: on-failure
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/docs/openapi3.yml
    volumes:
      - ./build/api-spec:/usr/share/nginx/html/docs
